[sys]

# the character set the input is in. DEFCON uses latin1, so that's what the DedCon
# event log will contain by default, so we should expect that.
charsetIn latin1

# the character set the configuration files are written in. All the real commands
# only use ASCII, so this does not really matter as long as those are represented
# as single bytes. Pick utf-8 or latin1 again.
charsetOut utf-8

[files]

# the output files

# the files containing the automatic bans
ban = auto_ban.txt

# the file containing the automatic warnings
warning = auto_warn.txt

# the database file
database = griefer.db

[policies]

# policies: when should a player be warned resp. banned?
# The general condition for a warning resp. a ban is
# (ban|warn)Offset + perGameOffset * timesPlayed + perDayOffset * days < griefSeverity
# where timesPlayed is the number of games the player has
# participated in since the first time he was logged as a griefer,
# griefSeverity is the sum of the severities of all his griefings,
# and days is the number of days since the last griefing by this player.

# Entries are purged from the database if the equation
# purgeOffset + perGameOffset * timesPlayed + perDayOffset * days/2 > griefSeverity
# is fulfilled.

perDayOffset = .2
perGameOffset = 1
banOffset = 10
warnOffset = 3
purgeOffset = 0

# this message is given as a warning:
warnMessage = WARNING: you have been naughty and the automatic Santa Claus has you on his list. Better behave, or you get banned.

[severities]

# you can configure the individual severities of the various griefing
# forms in this section.

voteKick = 4
earlyQuit = 3
noReady = 4
adminKick = 6
spam = 6

