[sys]

# the character set the configuration files are written in. All the real commands
# only use ASCII, so this does not really matter as long as those are represented
# as single bytes. Pick utf-8 or latin1 again.
charsetOut = utf-8

# IP adresses are suppressed in the output by default. If you want to show them,
# change the following option.
hideIP = yes

[files]

# the output files

# this file contains a text table with the player scores. The lines are formatted as
# <MinScore> <Score> <IDType> <ID> <Name>
# where <Score> is the best estimate for the player's score, <MinScore> the lower
# error bound thereof, <ID> the player's ID (either the KeyID or IP, and <IDType> tells you which)
# and <Name> is the name the player used last. It spans the whole rest of the line.
text = rating.txt

# this file contains the same data as a HTML table body for direct inclusion into
# web pages; the table rows are Lower MinScore, Score, MaxScore, GamesPlayed, GamesMissed, ID,
# and Name.
# MaxScore is the upper error bound of the player's score, GamesPlayed is the number of
# games played on the server, and ID is the combination of <IDType> and <ID> from rating.txt.
# GamesMissed is the number of games the player took part in without anyone entering the
# scores.
# You need to wrap the file into a <table> </table> tag pair and add a <th> row if you like.
html = rating.html

# the number of players in the database that did not make it into the list for having an
# infinitely low lowest score bound is logged into this file:
unrated = unrated.txt

# the database file
database = rating.db

# a file of dynamic IP users. Regular players are tracked via their KeyID which
# is unique; steam users and demo payers are tracked over their IP. Steam users
# and demo players with dynamic IP can only be tracked via entries in this file;
# each line corresponds to one user and has the form
# <beginning of IP address> <player name>
# for example, zjoere, a demo user, is tracked with the three entries (without the
# leading #, of course)
# 80.200 zjoere
# 81.241 zjoere
# 217.136 zjoere
# the player is then tracked by name only.
ipranges = ipranges.txt

# basic ranking constants
[score]
# minimal and maximal effective score. Players can have a lower or higher score,
# but when the influence on others is calcualted, the score is clamped to lie
# inside these bounds.
min = -1000
max = 10000

# constant that determines the spacing of players' scores. A score difference
# equal to this value between two players means the one with the higher score
# beats the other about 90% of the time.
range = 100

# once a player is in the database, games he participated in without
# entering the scores count for the error bars as if he had lost 
# previous games. This setting is the number of points that is subtracted
# from his score for every "missed" game:
missed = 1.0

# a certain amount of "missed" games can be tolerated without penalty, there
# are always possible RL reasons. This setting is the amount of missed games
# tolerated for every games with scores entered.
missedTolerance = 0.1

# The minimal number of games assumed to be played for the error calculation.
# Higer values artificially increase the error bars of players with a small
# number of rated games.
minWeight = 2.0

# to appear in the printed stat lists, a player needs to have played at least
# that many games (can be fractional because decay reduces the effective number
# of games someone has played):
minGames = 0.5

# as long as a player does not have at least so many games played, he is
# considered an apprentice and all influence of him on others will be scaled down.
# it will grow linearily from zero to the full weight of a fully accepted player.
apprenticeGames = 1.0

# "unreliable" players, those that are only identified via their IP, get a separate
# setting.
apprenticeGamesUnreliable = 3.0

# score stabilization only continues while scores move more than this each iteration:
minEps = 0.1

# and it does not run over more than this many iterations:
maxIterations = 10

# to stabilize the scores, a phantom player can be added.
[phantom]
# its score is fixed to this value:
score = 600

# the system pretends the phantom has played this many games against everyone else:
# (non-integer values are perfectly possible)
weight = 1.0

# if the number of games a player has played times this number is less than "weight",
# the product is used instead of weight. This can be used to limit the influence
# of players who went inactive on those who played against them.
relativeweight = 1.0

# and won them with this probability (in percent):
skill = 90.0

# the range of its influence is icreased relative to the regular ranges by this
# factor:
range = 1.0

# different stats are collected by the system; in this section, you can tune
# how they influence the player ranking. For each stat type and player pair, 
# the database contains a number of points each of the two players was able
# to score for himself. The points have different meaning for the different stats.
[weights]

# in the 'win' stat, a point for player A against player B means that A was a
# winner (player of highest score; for equal scores, there may be many winners ) 
# in a game where B participated, but was not a winner.
win = 1.0

# in the 'position' stat, a point for player A against player B means that A had
# a higher score than B in one game. In 1 vs 1, this is the same as the 'win' stat.
position = 0.0

# For each game A and B participate in where A has a higher score than B, player A
# gets awarded the score difference of the two in this stat.
# Two games with a score difference of 20 are worth the same as one game with
# a score difference of 40.
difference = 0.0

# For each game A and B participate in, each gets his own score as points in the 'clamped'
# stat. Scores below zero are clamped to zero.
clamped = 0.0

# For each game A and B participate in, each gets his own score as points in the 'score'
# stat (just like the 'clamped' stat); but instead of clamping negative socres, all
# scores are increased by the same amount to make all scores non-negative.
score = 0.0

# the team variations work exactly like the single player versions, but instead
# of the individual scores, the scores of players who are in alliances negotiated
# before the game starts are averaged.
teamwin = 0.0
teamposition = 0.0
teamscore = 0.0
teamdifference = 0.0
teamclamped = 0.0

# The weights above are applied when the player ranks are calculated. The settings
# below have the same net effect, but are activated while the event logs are parsed and
# before the games are written into the database. You can use them to adapt to setting
# changes that affect the scores, for example population size changes. The defaults are
# picked to make sense with default population.
# If the prescale for a stat type is zero, it is not logged into the database at all.
[prescale]
win = 1.0
position = 1.0
difference = 0.01
clamped = 0.01
score = 0.01
teamwin = 1.0
teamposition = 1.0
teamscore = 0.01
teamdifference = 0.01
teamclamped = 0.01

# special prescale value for pairings involving at least one DEMO player.
# set to 0 to keep DEMO players out of the database.
demo = 1.0

# after the decay command is issued, database entries with low importance are discarded.
[decay]
# players with less than this many games (yeah, the game count can be fractional after decays)
# are deleted.
player = .5

# games with less statistical weight than this get deleted.
games = .25

# settings governing selective amnesia
[amnesia]
# The maximal total weight of all games of a player combined. The rating will be roughly
# influenced by this many previous encounters of each player.
MaxWeight = 40

# The base decay rate. Every game decays at least at this rate.
Base = 1

# The distance based decay rate. On top of the base decay rate, a decay rate of
# Distance*RatingDifference/Range is added.
Distance = 6

# selective amnesia then lets each game decay with a rate proportional to
# Base + Distance*RatingDifference/Range, selecting the overall scale so
# that afterwards, the total weight of games for each player does not exceed
# MaxWeight.
