# -*- Makefile -*- for Defcon

#
# In the parent directory of source/ contrib/ targets/
#
# make -f targets/linux/Makefile.release
# 

export APBUILD_CC = g++-4.0
export APBUILD_CXX1 = g++-4.0

CXX=g++
CC=gcc
CXXFLAGS_BASE=-O3 -fpermissive -Wno-error=format-security -DEIGHTPLAYER
CPPFLAGS_BASE=
SUFFIX=

-include targets/linux/Makefile