DefconExpanded 1v1 Best Setups Only!
DefconExpanded 1v1 Best Setups Only! Second Server
DefconExpanded 1v1 Cursed Setups Only!
DefconExpanded 1v1 Totally Random
DefconExpanded 1v1 Totally Random - Second Server
DefconExpanded 1v1 UK and Ireland
DefconExpanded 1v1 Default
DefconExpanded 1v1 Lots of Units!
DefconExpanded 1v1 Christmas Tournament
DefconExpanded 1v1 Christmas Tournament Second Server
New Players Welcome Come and Play
DefconExpanded Training
DefconExpanded Diplomacy UK and Ireland
DefconExpanded 2v2 Max Cities - Pop
DefconExpanded 2v2 Totally Random
DefconExpanded 2v2 Totally Random Second Server
DefconExpanded 2v2 UK and Ireland
Sony and Hoov's Hideout
DefconExpanded 3v3 Totally Random
DefconExpanded 3v3 Totally Random - Second Server
DefconExpanded Free For All Random Cities
