#!/bin/bash

python3 "python_parsers/DefconExpanded Discord Bot.py" \
dedcon_game_events/game_events_DefconExpanded_1v1_Totally_Random.log:"1v1 Random" dedcon_server_logs/server_output_DefconExpanded_1v1_Totally_Random.log \
dedcon_game_events/game_events_DefconExpanded_1v1_Totally_Random_Second_Server.log:"1v1 Random Second" dedcon_server_logs/server_output_DefconExpanded_1v1_Totally_Random_Second_Server.log \
dedcon_game_events/game_events_DefconExpanded_1v1_Lots_of_Units.log:"1v1 Lots of Units" dedcon_server_logs/server_output_DefconExpanded_1v1_Lots_of_Units.log \
dedcon_game_events/game_events_DefconExpanded_1v1_Best_Setups_Only.log:"1v1 Best Setups" dedcon_server_logs/server_output_DefconExpanded_1v1_Best_Setups_Only.log \
dedcon_game_events/game_events_Raizers_Russia_vs_USA_Totally_Random.log:"1v1 Raizer's Server" dedcon_server_logs/server_output_Raizers_Russia_vs_USA_Totally_Random.log \
dedcon_game_events/game_events_DefconExpanded_1v1_Best_Setups_Only_Second_Server.log:"1v1 Best Setups" dedcon_server_logs/server_output_DefconExpanded_1v1_Best_Setups_Only_Second_Server.log \
dedcon_game_events/game_events_DefconExpanded_1v1_Cursed_Setups_Only.log:"1v1 Cursed Setups" dedcon_server_logs/server_output_DefconExpanded_1v1_Cursed_Setups_Only.log \
dedcon_game_events/game_events_DefconExpanded_1v1_Default.log:"1v1 Default" dedcon_server_logs/server_output_DefconExpanded_1v1_Default.log \
dedcon_game_events/game_events_DefconExpanded_1v1_UK_and_Ireland.log:"1v1 UK and Ireland" dedcon_server_logs/server_output_DefconExpanded_1v1_UK_and_Ireland.log \
dedcon_game_events/game_events_DefconExpanded_2v2_UK_and_Ireland.log:"2v2 UK and Ireland" dedcon_server_logs/server_output_DefconExpanded_2v2_UK_and_Ireland.log \
dedcon_game_events/game_events_DefconExpanded_Diplomacy_UK_and_Ireland.log:"Diplomacy UK and Ireland" dedcon_server_logs/server_output_DefconExpanded_Diplomacy_UK_and_Ireland.log \
dedcon_game_events/game_events_New_Players_Welcome_Come_and_Play.log:"New Player Server" dedcon_server_logs/server_output_New_Players_Welcome_Come_and_Play.log \
dedcon_game_events/game_events_DefconExpanded_Training.log:"Training Server" dedcon_server_logs/server_output_DefconExpanded_Training.log \
dedcon_game_events/game_events_DefconExpanded_2v2_Totally_Random.log:"2v2 Random" dedcon_server_logs/server_output_DefconExpanded_2v2_Totally_Random.log \
dedcon_game_events/game_events_DefconExpanded_2v2_Totally_Random_Second_Server.log:"2v2 Random Second" dedcon_server_logs/server_output_DefconExpanded_2v2_Totally_Random_Second_Server.log \
dedcon_game_events/game_events_DefconExpanded_2v2_Max_Cities_Pop.log:"2v2 Max Cities/Pop" dedcon_server_logs/server_output_DefconExpanded_2v2_Max_Cities_Pop.log \
dedcon_game_events/game_events_DefconExpanded_Free_For_All_Random_Cities.log:"FFA Server" dedcon_server_logs/server_output_DefconExpanded_Free_For_All_Random_Cities.log \
dedcon_game_events/game_events_DefconExpanded_3v3_Totally_Random.log:"3v3 Random" dedcon_server_logs/server_output_DefconExpanded_3v3_Totally_Random.log \
dedcon_game_events/game_events_DefconExpanded_3v3_Totally_Random_Second_Server.log:"3v3 Random Second" dedcon_server_logs/server_output_DefconExpanded_3v3_Totally_Random_Second_Server.log \
dedcon_game_events/game_events_MURICON_1v1_Totally_Random_2_8_15.log:"Muricon 1v1 Random" dedcon_server_logs/server_output_MURICON_1v1_Totally_Random_2_8_15.log \
dedcon_game_events/game_events_509_CG_2v2_Totally_Random_2_8_15.log:"509 CG 2v2" dedcon_server_logs/server_output_509_CG_2v2_Totally_Random_2_8_15.log \
dedcon_game_events/game_events_MURICON_1v1_Default_2_8_15.log:"Muricon 1v1" dedcon_server_logs/server_output_MURICON_1v1_Default_2_8_15.log \
dedcon_game_events/game_events_MURICON_UK_Mod.log:"Muricon UK Mod" dedcon_server_logs/server_output_MURICON_UK_Mod.log \
dedcon_game_events/game_events_DefconExpanded_4v4_Totally_Random.log:"4v4 Random" dedcon_server_logs/server_output_DefconExpanded_4v4_Totally_Random.log \
dedcon_game_events/game_events_DefconExpanded_8_Player_Diplomacy.log:"8 Player Diplo" dedcon_server_logs/server_output_DefconExpanded_8_Player_Diplomacy.log \
dedcon_game_events/game_events_DefconExpanded_5v5_Totally_Random.log:"5v5 Random" dedcon_server_logs/server_output_DefconExpanded_5v5_Totally_Random.log \
dedcon_game_events/game_events_DefconExpanded_10_Player_Diplomacy.log:"10 Player Diplo" dedcon_server_logs/server_output_DefconExpanded_10_Player_Diplomacy.log \
dedcon_game_events/game_events_DefconExpanded_16_Player_Test_Server.log:"16 Player Server" dedcon_server_logs/server_output_DefconExpanded_16_Player_Test_Server.log \
dedcon_game_events/game_events_DefconExpanded_2v2_Tournament.log:"2v2 Tournament" dedcon_server_logs/server_output_DefconExpanded_2v2_Tournament.log \
dedcon_game_events/game_events_DefconExpanded_1v1_Christmas_Tournament.log:"1v1 Christmas Tournament" dedcon_server_logs/server_output_DefconExpanded_1v1_Christmas_Tournament.log \
dedcon_game_events/game_events_Sony_and_Hoovs_Hideout.log:"Sony/Hoovs Hideout" dedcon_server_logs/server_output_Sony_and_Hoovs_Hideout.log \
dedcon_game_events/game_events_DefconExpanded_Test_Server.log:"Test Server" dedcon_server_logs/server_output_DefconExpanded_Test_Server.log \
dedcon_game_events/game_events_DefconExpanded_1v1_AF_vs_AS.log:"1v1 AF vs AS" dedcon_server_logs/server_output_DefconExpanded_1v1_AF_vs_AS.log
